version: "3.8"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_DATABASE: "wikidb"
        labels:
            NAME: "mongodb1"
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/db --quiet
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 10s